<a href="https://colab.research.google.com/github/p-cuadros/curso_python/blob/master/02ejerc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Dataset
La dataset que se usará es la muy conocida "Iris flower" (https://www.kaggle.com/arshid/iris-flower-dataset/version/1) .

La dataset contiene 150 samples (muestra individual), con 50 samples por cada una de la especies de Iris (Iris Setosa, Iris virginica, and Iris versicolor). 
Cada uno de los samples  tiene cuatros características:

* Petal length
* Petal width
* Sepal length
* Sepal width
* Class (Especie)


# Sección nueva

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [0]:
iris = pd.read_csv('iris.csv')

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X= iris.iloc[:,0:4]

In [0]:
y= iris['species']

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=20)

In [0]:
from sklearn.svm import SVC

In [0]:
model = SVC(gamma='auto')

In [24]:
model.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [25]:
predic = model.predict(X_test)
predic

array(['Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor'], dtype=object)

In [0]:
from sklearn.metrics import classification_report, confusion_matrix

In [28]:
print(confusion_matrix(y_test,predic))

[[13  0  0]
 [ 0 18  0]
 [ 0  2 12]]


In [29]:
print(classification_report(y_test, predic))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        13
Iris-versicolor       0.90      1.00      0.95        18
 Iris-virginica       1.00      0.86      0.92        14

       accuracy                           0.96        45
      macro avg       0.97      0.95      0.96        45
   weighted avg       0.96      0.96      0.96        45

