In [0]:
import numpy as np

In [0]:
lista=[1,2,3,4,5]

In [0]:
ar=np.array(lista)

In [4]:
ar

array([1, 2, 3, 4, 5])

In [5]:
type(ar)

numpy.ndarray

In [0]:
matriz = [[1,2],[3,4]]

In [7]:
np.array(matriz)

array([[1, 2],
       [3, 4]])

In [8]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.random.rand(7)

array([0.52263354, 0.07090978, 0.41812909, 0.7945819 , 0.57241095,
       0.74215649, 0.15399543])

In [0]:
arint = np.random.randint(1,150,25)

In [18]:
arint

array([ 74,  94,  89,  19,  22, 109, 129, 106,  17,  57,  53,  14,  28,
       148,  22,  23, 128, 127,  71,  47,  21, 104, 110,  23,  28])

In [19]:
arint.reshape(5,5)

array([[ 74,  94,  89,  19,  22],
       [109, 129, 106,  17,  57],
       [ 53,  14,  28, 148,  22],
       [ 23, 128, 127,  71,  47],
       [ 21, 104, 110,  23,  28]])

In [23]:
arint.max()

148

In [22]:
arint.min()

14

In [24]:
arint.argmax()

13

In [0]:
ar = np.arange(0,13)

In [26]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [27]:
ar[6]

6

In [28]:
ar[0:5]

array([0, 1, 2, 3, 4])

In [29]:
ar[:5]

array([0, 1, 2, 3, 4])

In [30]:
ar[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [0]:
ar[0:5]=50

In [32]:
ar

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10, 11, 12])

In [0]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [36]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
mat[2][1]

8

In [40]:
mat[2,1]

8

In [0]:
ar = np.arange(0,10)

In [0]:
resp_ar = ar>6

In [43]:
resp_ar

array([False, False, False, False, False, False, False,  True,  True,
        True])

In [44]:
ar[resp_ar]

array([7, 8, 9])

In [45]:
ar + ar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [46]:
ar + 50

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [47]:
np.sqrt(ar)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [48]:
np.max(ar)

9

In [49]:
mat.sum()

45

In [50]:
mat.sum(axis=0)

array([12, 15, 18])

In [51]:
mat.sum(axis=1)

array([ 6, 15, 24])